import Head from "next/head";
import { Button, Checkbox, Form, Input } from "antd";
import Axios from "axios";
import { useRouter } from "next/router";
import Header from "../components/Header";
import Footer from "../components/Footer";
export default function Home() {
  const router = useRouter();
  const onFinish = async (values: any) => {
    const response = await Axios.post(
      "http://localhost:3001/api/user/login",
      values
    );
    if (response) router.push("/home");
  };

  const onFinishFailed = (errorInfo: any) => {
    console.log("Failed:", errorInfo);
  };
  return (
    <div className="artile">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      {/* <Button shape="circle">Primary btn</Button> */}

      <main className="flex items-center justify-center mt-10 px-5 py-5 flex-col ">
        <Form
          name="basic"
          labelCol={{ span: 8 }}
          wrapperCol={{ span: 16 }}
          initialValues={{ remember: true }}
          onFinish={onFinish}
          onFinishFailed={onFinishFailed}
          autoComplete="off"
          // style={{
          //   width: "100%",
          //   display: "flex",
          //   flexDirection: "column",
          //   // alignItems: "center",
          //   justifyContent: "center",
          // }}
        >
          <Form.Item
            label="Username"
            name="username"
            rules={[{ required: true, message: "Please input your username!" }]}
          >
            <Input />
          </Form.Item>

          <Form.Item
            label="Password"
            name="password"
            rules={[{ required: true, message: "Please input your password!" }]}
          >
            <Input.Password />
          </Form.Item>

          {/* <Form.Item
            name="remember"
            valuePropName="checked"
            wrapperCol={{ offset: 8, span: 16 }}
          >
            <Checkbox>Remember me</Checkbox>
          </Form.Item> */}

          <Form.Item wrapperCol={{ offset: 8, span: 16 }}>
            <Button
              type="primary"
              htmlType="submit"
              style={{ backgroundColor: "blue" }}
            >
              Submit
            </Button>
          </Form.Item>
        </Form>
        {/* <div>
          <Image src={hospital} alt="hospital" />
        </div> */}
        <div>
          <img
            src="https://img.freepik.com/free-vector/people-walking-sitting-hospital-building-city-clinic-glass-exterior-flat-vector-illustration-medical-help-emergency-architecture-healthcare-concept_74855-10130.jpg?w=2000&t=st=1669952093~exp=1669952693~hmac=0769427c4c561bdde5f1da0f020166421d2a01c4f623c9a1e38d4e6ae40daacb"
            alt="hospital"
            style={{
              width: "600px",
              height: "auto",
            }}
          />
        </div>
      </main>

      <Footer />
    </div>
  );
}
